ax.localization:Register("de", {
    ["category.zones"] = "Zonen",
    ["subcategory.zones"] = "Zonen",
    ["subcategory.tracking"] = "Verfolgung",
    ["subcategory.editor"] = "Editor",
    ["subcategory.debug"] = "Debug",

    ["config.zones.tracking.server_interval"] = "Server-Tracking-Intervall",
    ["config.zones.tracking.client_interval"] = "Client-Tracking-Intervall",
    ["config.zones.tracking.hysteresis_time"] = "Hysterese-Umschaltverzoegerung",
    ["config.zones.tracking.hysteresis_margin"] = "Hysterese-Prioritätsabstand",
    ["config.zones.tracking.use_last_dominant"] = "Letzte dominante Zone verwenden",
    ["config.zones.editor.default_priority"] = "Standardpriorität für neue Zonen",
    ["config.zones.editor.default_box_extent"] = "Standardgroesse neuer Boxen",
    ["config.zones.editor.default_radius"] = "Standardradius",
    ["config.zones.editor.max_radius"] = "Maximaler Radius",
    ["config.zones.debug.enabled"] = "Zonen-Debug aktiviert",
    ["config.zones.debug.draw_distance"] = "Debug-Zeichendistanz",
    ["config.zones.debug.max_entries"] = "Maximale Debug-HUD-Einträge",
    ["config.zones.debug.target_tolerance"] = "Debug-Zieltoleranz",

    ["option.zones.debug.active"] = "Zonen-Debug",
    ["option.zones.debug.world"] = "Weltgeometrie",
    ["option.zones.debug.hud"] = "Debug-HUD",
    ["option.zones.debug.labels"] = "Zonenbeschriftungen",
    ["option.zones.debug.static"] = "Statische Zonen anzeigen",
    ["option.zones.debug.target"] = "Blickziel hervorheben",
    ["option.zones.debug.distance"] = "Zeichendistanz",
    ["option.zones.debug.entries"] = "HUD-Eintragsanzahl",

    ["zones.type.box"] = "Box",
    ["zones.type.box.summary"] = "Physisches Volumen mit zwei Ecken. Ideal für Räume, Strassen und Innenbereiche.",
    ["zones.type.sphere"] = "Kugel",
    ["zones.type.sphere.summary"] = "Physische Radialzone um einen Mittelpunkt. Gut für Kuppeln und kreisfoermige Bereiche.",
    ["zones.type.pvs"] = "PVS",
    ["zones.type.pvs.summary"] = "Sichtbarkeitszone, die reagiert, wenn Spieler den Ursprung sehen koennen.",
    ["zones.type.trace"] = "Trace",
    ["zones.type.trace.summary"] = "Sichtlinien-Zone, die einen freien Trace zum Ursprung benoetigt.",

    ["zones.common.new_zone"] = "Neue Zone",
    ["zones.common.zone"] = "Zone",
    ["zones.common.unnamed"] = "Unbenannt",
    ["zones.common.none"] = "keine",
    ["zones.common.unsaved"] = "ungespeichert",
    ["zones.common.type_priority"] = "%s  |  Priorität %d",

    ["zones.source.runtime"] = "Laufzeit",
    ["zones.source.static"] = "statisch",

    ["zones.summary.none"] = "Keine Zone geladen.",
    ["zones.summary.box"] = "Box %.0f x %.0f x %.0f",
    ["zones.summary.sphere"] = "Kugel Radius %.0f",
    ["zones.summary.radial"] = "%s Radius %.0f",
    ["zones.summary.origin_only"] = "%s nur Ursprung",

    ["zones.value_type.string"] = "String",
    ["zones.value_type.number"] = "Zahl",
    ["zones.value_type.boolean"] = "Boolean",
    ["zones.value_type.vector"] = "Vektor",
    ["zones.value_type.angle"] = "Winkel",
    ["zones.value_type.table"] = "Tabelle",
    ["zones.value_type.unknown"] = "unbekannt",

    ["zones.editor.title"] = "Zonen-Editor",
    ["zones.editor.section.workflow"] = "Ablauf",
    ["zones.editor.section.workflow.subtitle"] = "Erstelle, wähle und stelle Entwürfe wieder her, ohne Noclip zu verlassen.",
    ["zones.editor.section.saved"] = "Gespeicherte Zonen",
    ["zones.editor.section.saved.subtitle"] = "Laufzeit- und statische Zonen auf dieser Map.",
    ["zones.editor.section.draft"] = "Aktueller Entwurf",
    ["zones.editor.section.draft.subtitle"] = "Bearbeite die Arbeitskopie, bevor du sie speicherst.",
    ["zones.editor.section.flags"] = "Flags",
    ["zones.editor.section.flags.subtitle"] = "Fuege kleine Einstellungen wie safe, pvp oder eigene Bool-Werte hinzu.",
    ["zones.editor.section.data"] = "Daten",
    ["zones.editor.section.data.subtitle"] = "Speichere zusätzliche Zonendaten wie Text, Zahlen oder Vektoren.",
    ["zones.editor.section.actions"] = "Aktionen",
    ["zones.editor.section.actions.subtitle"] = "Speichere den Entwurf oder führe Aktionen auf der ausgewählten gespeicherten Zone aus.",

    ["zones.editor.button.select_look_target"] = "Blickziel auswählen",
    ["zones.editor.button.revert_to_saved"] = "Auf gespeicherten Stand zurücksetzen",
    ["zones.editor.button.new_box"] = "Neue Box",
    ["zones.editor.button.new_sphere"] = "Neue Kugel",
    ["zones.editor.button.new_pvs"] = "Neue PVS",
    ["zones.editor.button.new_trace"] = "Neuer Trace",
    ["zones.editor.button.rename"] = "Umbenennen",
    ["zones.editor.button.priority"] = "Priorität",
    ["zones.editor.button.use_box"] = "Als Box verwenden",
    ["zones.editor.button.use_sphere"] = "Als Kugel verwenden",
    ["zones.editor.button.use_pvs"] = "Als PVS verwenden",
    ["zones.editor.button.use_trace"] = "Als Trace verwenden",
    ["zones.editor.button.add_flag"] = "Flag hinzufügen",
    ["zones.editor.button.add_data"] = "Dateneintrag hinzufügen",
    ["zones.editor.button.save_draft"] = "Entwurf speichern",
    ["zones.editor.button.duplicate_zone"] = "Zone duplizieren",
    ["zones.editor.button.teleport_to_zone"] = "Zur Zone teleportieren",
    ["zones.editor.button.delete_zone"] = "Zone löschen",
    ["zones.editor.button.corner_a_look"] = "Ecke A vom Blick",
    ["zones.editor.button.corner_a_me"] = "Ecke A von mir",
    ["zones.editor.button.corner_b_look"] = "Ecke B vom Blick",
    ["zones.editor.button.corner_b_me"] = "Ecke B von mir",
    ["zones.editor.button.reset_box"] = "Box um mich zurücksetzen",
    ["zones.editor.button.use_look_position"] = "Blickposition verwenden",
    ["zones.editor.button.use_my_position"] = "Meine Position verwenden",
    ["zones.editor.button.set_radius"] = "Radius setzen",

    ["zones.editor.context_open"] = "Interaktion: C ist offen. Klicke auf alles, was du brauchst.",
    ["zones.editor.context_closed"] = "Interaktion: Halte C, um den Editor zu bedienen. Loslassen, um weiterzufliegen.",
    ["zones.editor.loaded_zones"] = "Geladene Zonen: %d",
    ["zones.editor.no_saved_zones"] = "Keine gespeicherten Zonen auf dieser Map.",
    ["zones.editor.zone_button"] = "#%d  %s",
    ["zones.editor.zone_meta"] = "%s  |  Priorität %d  |  %s",
    ["zones.editor.no_entries"] = "Noch keine Einträge.",
    ["zones.editor.property_row"] = "%s = %s",
    ["zones.editor.geometry_empty"] = "Wähle eine gespeicherte Zone oder erstelle einen neuen Entwurf.",
    ["zones.editor.corner_a"] = "Ecke A: %s",
    ["zones.editor.corner_b"] = "Ecke B: %s",
    ["zones.editor.center"] = "Mittelpunkt: %s",
    ["zones.editor.origin"] = "Ursprung: %s",
    ["zones.editor.radius"] = "Radius: %s",
    ["zones.editor.name_value"] = "Name: %s",
    ["zones.editor.type_value"] = "Typ: %s",
    ["zones.editor.priority_value"] = "Priorität: %s",
    ["zones.editor.geometry_value"] = "Geometrie: %s",
    ["zones.editor.saved_state_value"] = "Gespeicherter Status: %s",
    ["zones.editor.saved_state_editing"] = "bearbeitet Zone #%d",
    ["zones.editor.saved_state_new"] = "neuer Entwurf",
    ["zones.editor.footer_static"] = "Statische Zonen koennen angezeigt und dupliziert, aber im Editor weder überschrieben noch geloescht werden.",
    ["zones.editor.footer_runtime"] = "Gespeicherte änderungen laufen sofort durch das vorhandene Parallax-Zonen-Backend und werden an alle Clients synchronisiert.",
    ["zones.editor.selected_zone"] = "Ausgewählte Zone: #%d %s",
    ["zones.editor.selected_zone_none"] = "Ausgewählte Zone: keine",
    ["zones.editor.draft_status"] = "Entwurfsstatus: %s%s",
    ["zones.editor.draft_status_none"] = "Entwurfsstatus: keiner",
    ["zones.editor.look_target"] = "Blickziel: #%d",

    ["zones.editor.hud.title"] = "Zonen-Editor",
    ["zones.editor.hud.subtitle"] = "Halte C, um den Editor zu bedienen. Lass los, um weiterzufliegen.",
    ["zones.editor.hud.selected"] = "Ausgewählt: #%d %s",
    ["zones.editor.hud.selected_none"] = "Ausgewählt: keine",
    ["zones.editor.hud.look_target"] = "Blickziel: #%d",
    ["zones.editor.hud.look_target_none"] = "Blickziel: keine",
    ["zones.editor.hud.draft"] = "Entwurf: %s%s",
    ["zones.editor.hud.draft_none"] = "Entwurf: keiner",

    ["zones.debug.title"] = "Zonen-Debug",
    ["zones.debug.summary"] = "#%d %s | %s | p%d | %s | Flags %d | Daten %d",
    ["zones.debug.weight"] = " | w %.2f",
    ["zones.debug.counts"] = "Zonen: %d gesamt | %d Laufzeit | %d statisch",
    ["zones.debug.dominant"] = "Dominant: %s",
    ["zones.debug.target"] = "Ziel: %s",
    ["zones.debug.physical"] = "Physisch (%d):",
    ["zones.debug.visible"] = "Sichtbar (%d):",
    ["zones.debug.empty_entry"] = "  keine",
})
