ax.localization:Register("en", {
    ["subcategory.containers"] = "Containers",

    ["config.container.save"] = "Persist Containers",
    ["config.container.save.help"] = "Whether spawned containers persist across restarts.",
    ["config.container.default.open_time"] = "Default Container Open Time",
    ["config.container.default.open_time.help"] = "Fallback delay before a container opens when its definition does not override it.",
    ["config.container.default.max_weight"] = "Default Container Max Weight",
    ["config.container.default.max_weight.help"] = "Fallback maximum storage weight for containers without an explicit weight capacity.",
    ["config.container.password.attempt_limit"] = "Container Password Attempt Limit",
    ["config.container.password.attempt_limit.help"] = "Maximum password attempts allowed per locked container before further attempts are blocked.",
    ["config.container.password.retry_delay"] = "Container Password Retry Delay",
    ["config.container.password.retry_delay.help"] = "Delay in seconds between password submissions.",

    ["container.your_inventory"] = "Your Inventory",
    ["container.item_column"] = "Item",
    ["container.take_button"] = "<< Take",
    ["container.store_button"] = "Store >>",
    ["container.title"] = "Storage Container",
    ["container.contents_title"] = "Container",
    ["container.transfer_actions"] = "TRANSFER",
    ["container.drag_hint"] = "Drag items between panes or use the transfer buttons.",
    ["container.empty_inventory"] = "Nothing is stored here yet.",
    ["container.capacity"] = "Capacity: %s%s / %s%s",
    ["container.open_time"] = "Open Time: %.1fs",
    ["container.money"] = "Money: %d",
    ["container.move_items"] = "Move items between your inventory and this container.",
    ["container.opening"] = "Opening %s...",
    ["container.locked"] = "🔒 Locked",
    ["container.unlocked"] = "🔓 Unlocked",
    ["container.password.title"] = "Container Password",
    ["container.password.prompt"] = "Enter the password for this container:",
    ["container.password.incorrect"] = "That password was incorrect.",
    ["container.password.limit"] = "You have reached the password attempt limit.",
    ["container.not_ready"] = "This container is not ready yet.",
    ["container.search_your_inventory"] = "Search Your Inventory",
    ["container.search_container_inventory"] = "Search Container",

    ["container.property.set_password"] = "Set Password",
    ["container.property.set_password.prompt"] = "Enter a new password. Leave blank to clear it:",
    ["container.property.set_name"] = "Set Name",
    ["container.property.set_name.prompt"] = "Enter a new display name. Leave blank to reset it:",
    ["container.password.updated"] = "Container password updated.",
    ["container.password.cleared"] = "Container password cleared.",
    ["container.name.updated"] = "Container name updated.",
    ["container.name.reset"] = "Container name reset.",
})
