ax.localization:Register("fr", {
    ["subcategory.containers"] = "Conteneurs",

    ["config.container.save"] = "Persister les conteneurs",
    ["config.container.save.help"] = "Détermine si les conteneurs placés persistent après les redémarrages.",
    ["config.container.default.open_time"] = "Temps d'ouverture par défaut des conteneurs",
    ["config.container.default.open_time.help"] = "Délai de secours avant qu'un conteneur s'ouvre lorsque sa définition ne le surcharge pas.",
    ["config.container.default.max_weight"] = "Poids maximal par défaut des conteneurs",
    ["config.container.default.max_weight.help"] = "Poids de stockage maximal de secours pour les conteneurs sans capacité explicite.",
    ["config.container.password.attempt_limit"] = "Limite de tentatives de mot de passe des conteneurs",
    ["config.container.password.attempt_limit.help"] = "Nombre maximal de tentatives de mot de passe autorisées par conteneur verrouillé avant de bloquer les suivantes.",
    ["config.container.password.retry_delay"] = "Délai de réessai de mot de passe des conteneurs",
    ["config.container.password.retry_delay.help"] = "Délai en secondes entre les soumissions de mot de passe.",

    ["container.your_inventory"] = "Votre inventaire",
    ["container.item_column"] = "Objet",
    ["container.take_button"] = "<< Prendre",
    ["container.store_button"] = "Déposer >>",
    ["container.title"] = "Conteneur de stockage",
    ["container.contents_title"] = "Conteneur",
    ["container.transfer_actions"] = "TRANSFÉRER",
    ["container.drag_hint"] = "Glissez les objets entre les panneaux ou utilisez les boutons de transfert.",
    ["container.empty_inventory"] = "Rien n'est stocké ici pour le moment.",
    ["container.capacity"] = "Capacité : %s%s / %s%s",
    ["container.open_time"] = "Temps d'ouverture : %.1fs",
    ["container.money"] = "Argent : %d",
    ["container.move_items"] = "Déplacez des objets entre votre inventaire et ce conteneur.",
    ["container.opening"] = "Ouverture de %s...",
    ["container.locked"] = "🔒 Verrouillé",
    ["container.unlocked"] = "🔓 Déverrouillé",
    ["container.password.title"] = "Mot de passe du conteneur",
    ["container.password.prompt"] = "Entrez le mot de passe de ce conteneur :",
    ["container.password.incorrect"] = "Le mot de passe est incorrect.",
    ["container.password.limit"] = "Vous avez atteint la limite de tentatives de mot de passe.",
    ["container.not_ready"] = "Ce conteneur n'est pas encore prêt.",
    ["container.search_your_inventory"] = "Rechercher dans votre inventaire",
    ["container.search_container_inventory"] = "Rechercher dans le conteneur",

    ["container.property.set_password"] = "Définir le mot de passe",
    ["container.property.set_password.prompt"] = "Entrez un nouveau mot de passe. Laissez vide pour le supprimer :",
    ["container.property.set_name"] = "Définir le nom",
    ["container.property.set_name.prompt"] = "Entrez un nouveau nom d'affichage. Laissez vide pour réinitialiser :",
    ["container.password.updated"] = "Mot de passe du conteneur mis à jour.",
    ["container.password.cleared"] = "Mot de passe du conteneur supprimé.",
    ["container.name.updated"] = "Nom du conteneur mis à jour.",
    ["container.name.reset"] = "Nom du conteneur réinitialisé.",
})