ax.localization:Register("de", {
    ["subcategory.containers"] = "Container",

    ["config.container.save"] = "Container speichern",
    ["config.container.save.help"] = "Legt fest, ob gespawnte Container Neustarts überdauern.",
    ["config.container.default.open_time"] = "Standard-Öffnungszeit für Container",
    ["config.container.default.open_time.help"] = "Standardverzögerung, bevor sich ein Container öffnet, wenn die Definition keinen eigenen Wert setzt.",
    ["config.container.default.max_weight"] = "Standard-Maximalgewicht für Container",
    ["config.container.default.max_weight.help"] = "Standardmäßige maximale Traglast für Container ohne explizite Gewichtskapazität.",
    ["config.container.password.attempt_limit"] = "Limit für Container-Passwortversuche",
    ["config.container.password.attempt_limit.help"] = "Maximale Anzahl an Passwortversuchen pro gesperrtem Container, bevor weitere Versuche blockiert werden.",
    ["config.container.password.retry_delay"] = "Verzögerung zwischen Passwortversuchen",
    ["config.container.password.retry_delay.help"] = "Verzögerung in Sekunden zwischen Passwort-Eingaben.",

    ["container.your_inventory"] = "Dein Inventar",
    ["container.item_column"] = "Gegenstand",
    ["container.take_button"] = "<< Nehmen",
    ["container.store_button"] = "Lagern >>",
    ["container.title"] = "Lagercontainer",
    ["container.contents_title"] = "Containerinhalt",
    ["container.transfer_actions"] = "TRANSFER",
    ["container.drag_hint"] = "Ziehe Gegenstände zwischen die Bereiche oder nutze die Transferknöpfe.",
    ["container.empty_inventory"] = "Hier ist momentan nichts gelagert.",
    ["container.capacity"] = "Kapazität: %s%s / %s%s",
    ["container.open_time"] = "Öffnungszeit: %.1fs",
    ["container.money"] = "Geld: %d",
    ["container.move_items"] = "Verschiebe Gegenstände zwischen deinem Inventar und diesem Container.",
    ["container.opening"] = "%s wird geöffnet...",
    ["container.locked"] = "🔒 Gesperrt",
    ["container.unlocked"] = "🔓 Entsperrt",
    ["container.password.title"] = "Container-Passwort",
    ["container.password.prompt"] = "Gib das Passwort für diesen Container ein:",
    ["container.password.incorrect"] = "Dieses Passwort ist falsch.",
    ["container.password.limit"] = "Du hast das Limit für Passwortversuche erreicht.",
    ["container.not_ready"] = "Dieser Container ist noch nicht bereit.",
    ["container.search_your_inventory"] = "Inventar durchsuchen",
    ["container.search_container_inventory"] = "Container durchsuchen",

    ["container.property.set_password"] = "Passwort setzen",
    ["container.property.set_password.prompt"] = "Gib ein neues Passwort ein. Leer lassen, um es zu entfernen:",
    ["container.property.set_name"] = "Name setzen",
    ["container.property.set_name.prompt"] = "Gib einen neuen Anzeigenamen ein. Leer lassen, um ihn zurückzusetzen:",
    ["container.password.updated"] = "Container-Passwort aktualisiert.",
    ["container.password.cleared"] = "Container-Passwort entfernt.",
    ["container.name.updated"] = "Container-Name aktualisiert.",
    ["container.name.reset"] = "Container-Name zurückgesetzt.",
})
