name: Create Snapshot Branch

on:
  push:
    branches:
      - main

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Count human commits
        id: version
        run: |
          count=0
          for sha in $(git rev-list --reverse main); do
            author=$(git show -s --format='%ae' "$sha")
            if [[ "$author" != *"noreply.github.com" && "$author" != *"bot@"* ]]; then
              count=$((count+1))
            fi
          done

          echo "commit_count=$count" >> $GITHUB_OUTPUT
          echo "COMMIT_COUNT=$count" >> $GITHUB_ENV

      - name: Create snapshot branch
        run: |
          if (( COMMIT_COUNT > 417 && COMMIT_COUNT % 100 == 0 )); then
            major=$((COMMIT_COUNT / 1000))
            minor=$(((COMMIT_COUNT % 1000) / 100))
            tag="snapshot-$major.$minor"

            git config user.name "github-actions"
            git config user.email "github-actions@github.com"

            git checkout -b "$tag"
            git push origin "$tag"
          else
            echo "No snapshot needed at $COMMIT_COUNT commits."
          fi
